# Generated by Django 4.2.16 on 2024-10-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_applicantprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
    ]
