# Generated by Django 4.2.16 on 2024-10-11 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='application_deadline',
            new_name='applicationDeadline',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_description',
            new_name='jobDescription',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_title',
            new_name='jobTitle',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='salary_range',
            new_name='salaryRange',
        ),
    ]
