# Generated by Django 4.2.16 on 2024-10-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_application_deadline_job_applicationdeadline_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='employment_type',
            new_name='employmentType',
        ),
    ]
