# Generated by Django 4.2.16 on 2026-01-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_email'),
        ('jobs', '0004_jobapplication'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together={('job', 'applicant_profile')},
        ),
    ]
